export default {
  grid: {
    container: '130rem',
    gutter: '3.2rem',
  },
  border: {
    radius: '0.4rem',
  },
  font: {
    family:
      'Poppins, -apple-system, BlinkMacSystemFont, \'Segoe UI\', Roboto, Oxygen, Ubuntu, Cantarell, \'Open Sans\', \'Helvetica Neue\', sans-serif',
    light: 300,
    normal: 400,
    bold: 600,
    sizes: {
      xxxsmall: '0.8rem',
      xxsmall: '1rem',
      xsmall: '1.2rem',
      small: '1.4rem',
      medium: '1.6rem',
      large: '1.8rem',
      xlarge: '2.0rem',
      xxlarge: '2.8rem',
      huge: '5.2rem',
    },
  },
  colors: {
    mainBg: '#FAFAFA',
    primary: '#0385FC',
    primaryDark: '#0B61B0',
    secondaryDark: '#00B043',
    secondary: '#1CFC71',
    quartenary: '#FC271C',
    quartenaryDark: '#B00A02',
    ternary: '#FCD20F',
    ternaryDark: '#B09413',
    quaternary: '#FC610F',
    quaternaryDark: '#B04913',
    white: '#FFF',
    black: '#000',
    code: '#2f3337',
    pre: '#F6F6F6',
    grayLight: '#D9D9D9',
    gray: '#8B8B8B',
    grayDark: '#585858',
  },
  spacings: {
    xxsmall: '0.8rem',
    xsmall: '1.6rem',
    small: '2.4rem',
    medium: '3.2rem',
    large: '4.0rem',
    xlarge: '4.8rem',
    xxlarge: '5.6rem',
  },
  layers: {
    base: 10,
    menu: 20,
    overlay: 30,
    modal: 40,
    alwaysOnTop: 50,
  },
  transition: {
    default: '0.3s ease-in-out',
    fast: '0.1s ease-in-out',
  },
};
